package flogin;

import java.awt.Color;
import model.panelborder;
import model.buttonborder;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.hasil_order;
import model.mbarang;
import model.model_meja;
import model.rincian_order;
import program.receptioniss.db_connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author boipasta
 */
public class home extends javax.swing.JFrame {

    Connection con;
    Statement stat;
    String sql;
    ResultSet rs;
    int hakAkses;
    String anama = null;

    public List<rincian_order> rincian = new ArrayList<>();
    public model_meja mejaDipilih = new model_meja();

    public home(int hakakses) {
        hakAkses = hakakses;
        try {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            con = db_connection.getkoneksi();
            stat = con.createStatement();
            initComponents();
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadMeja();
    }

    private void loadMeja() {
        wadahm.removeAll();
        try {
            sql = "SELECT * FROM entri_meja";
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                model_meja meja = new model_meja();
                meja.setId_meja(rs.getInt("id_meja"));
                meja.setAtas_nama(rs.getString("atas_nama"));
                meja.setNo_meja(rs.getInt("no_meja"));

                wadahm.add(new TemplateMeja(this, meja));
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        wadahm.revalidate();
    }


    private void loadorder() {
        panelgridorder.removeAll();
        List<hasil_order> order = new hasil_order().get(con);
        order.forEach((t) -> {
            panelgridorder.add(new orderan(this,t, con));
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        admin = new javax.swing.JLabel();
        wadahmeja = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jentri = new buttonborder(30);
        jbarang = new buttonborder(30);
        jorder = new buttonborder(30);
        jtran = new buttonborder(30);
        jlaporan = new buttonborder(30);
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jhome = new javax.swing.JButton();
        jButton2 = new buttonborder(70);
        jButton1 = new buttonborder(70);
        bmenu = new javax.swing.JButton();
        jButton5 = new buttonborder(20);
        konten = new javax.swing.JPanel();
        home2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        entrib = new javax.swing.JPanel();
        entrior = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        panelgridbarang = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        nmeja = new javax.swing.JLabel();
        atasnama = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        totalbayar = new javax.swing.JLabel();
        totalbayar1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableorder = new javax.swing.JTable();
        jButton6 = new buttonborder(28);
        jButton3 = new buttonborder(28);
        jButton7 = new buttonborder(20);
        entrim = new javax.swing.JPanel();
        buttonorder = new buttonborder(20);
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tnomeja = new javax.swing.JTextField();
        tatasnama = new javax.swing.JTextField();
        panel = new panelborder(10);
        wadahm = new javax.swing.JPanel();
        glporan = new javax.swing.JPanel();
        tambahakun = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel5 = new panelborder(12);
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new buttonborder(20);
        jLabel8 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        namap = new javax.swing.JTextField();
        hakakses = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cpassword = new javax.swing.JPasswordField();
        jPanel6 = new panelborder(12);
        jLabel6 = new javax.swing.JLabel();
        pemesanan = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        order = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        panelgridorder = new javax.swing.JPanel();
        entrit = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        print = new javax.swing.JPanel();
        jPanel8 = new panelborder(20);
        jLabel17 = new javax.swing.JLabel();
        nomet = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        namat = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tanggalt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ttrant = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        totalt = new javax.swing.JTextField();
        bayart = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        uangkembali = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        namalabel = new javax.swing.JLabel();

        admin.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        admin.setText("Admin");

        wadahmeja.setBackground(new java.awt.Color(255, 0, 204));
        wadahmeja.setLayout(new java.awt.GridLayout(1, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Design by Bhoipasta");

        jentri.setBackground(new java.awt.Color(241, 243, 244));
        jentri.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jentri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chair-school24.png"))); // NOI18N
        jentri.setText("Entri Meja");
        jentri.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(241, 243, 244)));
        buttonGroup1.add(jentri);
        jentri.setContentAreaFilled(false);
        jentri.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chair-school28.png"))); // NOI18N
        jentri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jentriActionPerformed(evt);
            }
        });

        jbarang.setBackground(new java.awt.Color(241, 243, 244));
        jbarang.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/package.png"))); // NOI18N
        jbarang.setText("Entri Barang");
        jbarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(241, 243, 244)));
        buttonGroup1.add(jbarang);
        jbarang.setContentAreaFilled(false);
        jbarang.setIconTextGap(14);
        jbarang.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/package (1).png"))); // NOI18N
        jbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbarangActionPerformed(evt);
            }
        });

        jorder.setBackground(new java.awt.Color(241, 243, 244));
        jorder.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wallbarang24.png"))); // NOI18N
        jorder.setText("Entri Order");
        jorder.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(241, 243, 244)));
        buttonGroup1.add(jorder);
        jorder.setContentAreaFilled(false);
        jorder.setIconTextGap(14);
        jorder.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wallbarang.png"))); // NOI18N
        jorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorderActionPerformed(evt);
            }
        });

        jtran.setBackground(new java.awt.Color(241, 243, 244));
        jtran.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jtran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/truckorder.png"))); // NOI18N
        jtran.setText("Entri Transaksi");
        jtran.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(241, 243, 244)));
        buttonGroup1.add(jtran);
        jtran.setContentAreaFilled(false);
        jtran.setIconTextGap(8);
        jtran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/truck-delivery28.png"))); // NOI18N
        jtran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtranActionPerformed(evt);
            }
        });

        jlaporan.setBackground(new java.awt.Color(241, 243, 244));
        jlaporan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jlaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apps.png"))); // NOI18N
        jlaporan.setText("Laporan");
        jlaporan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 12, 0, 0, new java.awt.Color(241, 243, 244)));
        buttonGroup1.add(jlaporan);
        jlaporan.setContentAreaFilled(false);
        jlaporan.setIconTextGap(14);
        jlaporan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apps (1).png"))); // NOI18N
        jlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlaporanActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dad.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(18, 38, 63));
        jLabel3.setText("Reseptionis");

        jhome.setBackground(new java.awt.Color(255, 255, 255));
        jhome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home-circle24.png"))); // NOI18N
        jhome.setText("Home");
        jhome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(44, 123, 229)));
        buttonGroup1.add(jhome);
        jhome.setContentAreaFilled(false);
        jhome.setHideActionText(true);
        jhome.setIconTextGap(13);
        jhome.setRequestFocusEnabled(false);
        jhome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home-circle28.png"))); // NOI18N
        jhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhomeActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bmenu.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        bmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        bmenu.setText("Menu");
        bmenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(44, 123, 229)));
        bmenu.setContentAreaFilled(false);
        bmenu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu28.png"))); // NOI18N
        bmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmenuActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(44, 123, 229));
        jButton5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Logout");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkbox-marked-circle.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jhome, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jLabel2))
                        .addComponent(jentri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbarang, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addComponent(jorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jhome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jentri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jorder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jtran, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jlaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        konten.setBackground(new java.awt.Color(255, 255, 255));
        konten.setPreferredSize(new java.awt.Dimension(1366, 798));
        konten.setLayout(new java.awt.CardLayout());

        home2.setBackground(new java.awt.Color(248, 250, 252));

        jLabel1.setFont(new java.awt.Font("Questrial", 1, 48)); // NOI18N
        jLabel1.setText("RESTAURANT Bhoi PAsta ");

        javax.swing.GroupLayout home2Layout = new javax.swing.GroupLayout(home2);
        home2.setLayout(home2Layout);
        home2Layout.setHorizontalGroup(
            home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(422, Short.MAX_VALUE))
        );
        home2Layout.setVerticalGroup(
            home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        konten.add(home2, "card4");

        entrib.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout entribLayout = new javax.swing.GroupLayout(entrib);
        entrib.setLayout(entribLayout);
        entribLayout.setHorizontalGroup(
            entribLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1164, Short.MAX_VALUE)
        );
        entribLayout.setVerticalGroup(
            entribLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        konten.add(entrib, "card3");

        entrior.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(249, 249, 249));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 6, 0));

        panelgridbarang.setLayout(new java.awt.GridLayout(0, 2, 10, 10));
        jPanel3.add(panelgridbarang);

        jScrollPane1.setViewportView(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        nmeja.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        nmeja.setText("no meja");

        atasnama.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        atasnama.setText("Atas nama");

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel16.setText("Atas Nama");

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setText("no meja");

        totalbayar.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        totalbayar.setText("total");

        totalbayar1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        totalbayar1.setText("Total");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));

        tableorder.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tableorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Makanan&minuman", "Jumlah", "harga", "Sub total"
            }
        ));
        jScrollPane3.setViewportView(tableorder);

        jButton6.setBackground(new java.awt.Color(0, 153, 204));
        jButton6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Lanjutkan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("detail pemesanan");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atasnama)
                            .addComponent(nmeja))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(totalbayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton7)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalbayar1)
                            .addComponent(totalbayar))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(nmeja))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(atasnama))))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout entriorLayout = new javax.swing.GroupLayout(entrior);
        entrior.setLayout(entriorLayout);
        entriorLayout.setHorizontalGroup(
            entriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entriorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        entriorLayout.setVerticalGroup(
            entriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entriorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        konten.add(entrior, "card5");

        entrim.setBackground(new java.awt.Color(239, 239, 239));

        buttonorder.setBackground(new java.awt.Color(0, 153, 204));
        buttonorder.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        buttonorder.setForeground(new java.awt.Color(255, 255, 255));
        buttonorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/order.png"))); // NOI18N
        buttonorder.setText("Order");
        buttonorder.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/order28.png"))); // NOI18N
        buttonorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonorderActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 204));
        jLabel7.setText("No Meja");

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 204));
        jLabel12.setText("Atas Nama");

        tnomeja.setBackground(new java.awt.Color(239, 239, 239));
        tnomeja.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tnomeja.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 204)));
        tnomeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnomejaActionPerformed(evt);
            }
        });

        tatasnama.setBackground(new java.awt.Color(239, 239, 239));
        tatasnama.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tatasnama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 204)));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new java.awt.GridBagLayout());

        wadahm.setBackground(new java.awt.Color(255, 255, 255));
        wadahm.setLayout(new java.awt.GridLayout(0, 3, 12, 12));
        panel.add(wadahm, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout entrimLayout = new javax.swing.GroupLayout(entrim);
        entrim.setLayout(entrimLayout);
        entrimLayout.setHorizontalGroup(
            entrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entrimLayout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(entrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(entrimLayout.createSequentialGroup()
                        .addGroup(entrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addGap(34, 34, 34)
                        .addGroup(entrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tnomeja)
                            .addComponent(tatasnama, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buttonorder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        entrimLayout.setVerticalGroup(
            entrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entrimLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(entrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tnomeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(entrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tatasnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(buttonorder, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        konten.add(entrim, "card10");

        glporan.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout glporanLayout = new javax.swing.GroupLayout(glporan);
        glporan.setLayout(glporanLayout);
        glporanLayout.setHorizontalGroup(
            glporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1164, Short.MAX_VALUE)
        );
        glporanLayout.setVerticalGroup(
            glporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        konten.add(glporan, "card7");

        tambahakun.setLayout(new java.awt.GridLayout(1, 0));

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 153, 204));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 255));
        jLabel5.setText("<html><center>Buat Akun Untuk</center>\n<p>Kasir And Pelayan\n</html>");

        jButton4.setBackground(new java.awt.Color(255, 0, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Buat Akun");
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("Nama Pengguna");

        password.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 255)));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setText("Kata Sandi");

        namap.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        namap.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 255)));

        hakakses.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        hakakses.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 255)));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setText("Hak Akses");

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setText("Konfirmasi kata sandi");

        cpassword.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 255)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(41, 41, 41))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hakakses, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(password)
                                    .addComponent(namap)
                                    .addComponent(cpassword)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(namap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hakakses, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(27, 27, 27)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Questrial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(44, 123, 229));
        jLabel6.setText("<html><center>Buat Menu</center> \n<p>Makanan\n</html>");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tambahakun.add(kGradientPanel2);

        konten.add(tambahakun, "card8");

        pemesanan.setBackground(new java.awt.Color(0, 204, 204));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel14.setText("No Meja");

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel15.setText("Atas Nama");

        jTextField3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        javax.swing.GroupLayout pemesananLayout = new javax.swing.GroupLayout(pemesanan);
        pemesanan.setLayout(pemesananLayout);
        pemesananLayout.setHorizontalGroup(
            pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemesananLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(737, Short.MAX_VALUE))
        );
        pemesananLayout.setVerticalGroup(
            pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemesananLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pemesananLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(pemesananLayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(348, Short.MAX_VALUE))
        );

        konten.add(pemesanan, "card9");

        order.setBackground(new java.awt.Color(204, 204, 204));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        panelgridorder.setLayout(new java.awt.GridLayout(0, 2));
        jPanel7.add(panelgridorder);

        jScrollPane4.setViewportView(jPanel7);

        javax.swing.GroupLayout orderLayout = new javax.swing.GroupLayout(order);
        order.setLayout(orderLayout);
        orderLayout.setHorizontalGroup(
            orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1164, Short.MAX_VALUE)
        );
        orderLayout.setVerticalGroup(
            orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        konten.add(order, "card10");

        entrit.setBackground(new java.awt.Color(247, 246, 246));

        jButton8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton8.setText("Print");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        print.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel17.setText("No Meja");

        nomet.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nomet.setText("nomeja");

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel19.setText("Atas Nama");

        namat.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        namat.setText("atasnama");

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel21.setText("Tanggal");

        tanggalt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tanggalt.setText("tanggalt");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel17)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(namat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(nomet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(35, 35, 35)
                        .addComponent(tanggalt)
                        .addGap(39, 39, 39))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalt)
                    .addComponent(jLabel21)
                    .addComponent(nomet)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(namat))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        ttrant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(ttrant);

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel23.setText("total");

        totalt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        bayart.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bayart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayartKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bayartKeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel24.setText("bayar");

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel25.setText("kembalian");

        uangkembali.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("<html>Restoran Boipasta<br>\n<center>私はサイコパスです\n</html>");

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jLabel20.setText("<html>\n<center>Terima kasih,sudah memesan makanan kami</center>\n========== Layanan Konsumen BoiPasta==========\n</html>");

        javax.swing.GroupLayout printLayout = new javax.swing.GroupLayout(print);
        print.setLayout(printLayout);
        printLayout.setHorizontalGroup(
            printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(printLayout.createSequentialGroup()
                .addGroup(printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(printLayout.createSequentialGroup()
                                .addGroup(printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(31, 31, 31)
                                .addGroup(printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bayart)
                                    .addComponent(totalt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(printLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(31, 31, 31)
                                .addComponent(uangkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(printLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        printLayout.setVerticalGroup(
            printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(totalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(bayart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(printLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uangkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout entritLayout = new javax.swing.GroupLayout(entrit);
        entrit.setLayout(entritLayout);
        entritLayout.setHorizontalGroup(
            entritLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entritLayout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        entritLayout.setVerticalGroup(
            entritLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entritLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(entritLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        konten.add(entrit, "card6");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(243, 243, 243)));

        namalabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        namalabel.setText("home");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(namalabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namalabel)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(konten, javax.swing.GroupLayout.DEFAULT_SIZE, 1164, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(konten, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhomeActionPerformed
        konten.removeAll();
        konten.add(home2);
        konten.repaint();
        konten.revalidate();
        namalabel.setText(jhome.getText());
    }//GEN-LAST:event_jhomeActionPerformed

    private void jentriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jentriActionPerformed
        konten.removeAll();
        konten.add(entrim);
        konten.repaint();
        konten.revalidate();
        namalabel.setText(jentri.getText());
        loadMeja();
    }//GEN-LAST:event_jentriActionPerformed

    private void jbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarangActionPerformed
        konten.removeAll();
        konten.add(entrib);
        konten.repaint();
        konten.revalidate();
        namalabel.setText(jbarang.getText());
    }//GEN-LAST:event_jbarangActionPerformed

    private void jorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorderActionPerformed

        konten.removeAll();
        konten.add(entrior);
        konten.repaint();
        konten.revalidate();
        namalabel.setText(jorder.getText());
        loaddata();

    }//GEN-LAST:event_jorderActionPerformed

    private void jtranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtranActionPerformed
        konten.removeAll();
        konten.add(entrit);
        konten.repaint();
        konten.revalidate();
        namalabel.setText(jtran.getText());
    }//GEN-LAST:event_jtranActionPerformed

    private void jlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlaporanActionPerformed
        konten.removeAll();
        konten.add(glporan);
        konten.repaint();
        konten.revalidate();
        namalabel.setText(jlaporan.getText());
    }//GEN-LAST:event_jlaporanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int exit = JOptionPane.showConfirmDialog(this, "Yakin mau keluar?", "keluar", JOptionPane.YES_NO_OPTION);
        if (exit == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmenuActionPerformed
        konten.removeAll();
        konten.add(tambahakun);
        konten.repaint();
        konten.revalidate();
        namalabel.setText(bmenu.getText());
    }//GEN-LAST:event_bmenuActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int id = 0;
        String Password = password.getText();
        String confirmpassword = cpassword.getText();
        String namapengguna = namap.getText();
        String hakakses1 = hakakses.getText();
        if (Password.isEmpty() || confirmpassword.isEmpty() || namapengguna.isEmpty() || hakakses1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi kolom yang masih kosong");
            return;
        }
        if (!Password.equals(confirmpassword)) {
            JOptionPane.showMessageDialog(this, "pasword tidak sama");
            return;
        }
        String sql = "INSERT INTO pengguna VALUES (?,?,?,?)";
        try (PreparedStatement p = (PreparedStatement) con.prepareStatement(sql)) {
            p.setInt(1, 0);
            p.setString(2, namapengguna);
            p.setString(3, Password);
            p.setInt(4, Integer.parseInt(hakakses1));

            p.execute();
            p.close();
            JOptionPane.showMessageDialog(this, "berhasil membuat akun");
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            con.close();
            JOptionPane.showMessageDialog(this, "yakin logout");
            dispose();
            new flogin().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tnomejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnomejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnomejaActionPerformed

    private void buttonorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonorderActionPerformed

        if (tnomeja.getText().isEmpty() || tatasnama.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "silahkan pilih no meja dan masukan nama");
            return;
        }

        anama = tatasnama.getText();

        nmeja.setText(String.valueOf(mejaDipilih.getNo_meja()));
        atasnama.setText(anama);

        konten.removeAll();
        konten.add(entrior);
        konten.repaint();
        konten.revalidate();

        tnomeja.setText("");
        tatasnama.setText("");
        loaddata();

    }//GEN-LAST:event_buttonorderActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int total = 0;

        for (rincian_order rincianor : rincian) {
            total += rincianor.getTotalbarang() * rincianor.getHarga();
        }
        hasil_order hasil = new hasil_order();
        hasil.setAtasnama(atasnama.getText());
        hasil.setNomeja(Integer.parseInt(nmeja.getText()));
        hasil.setTotal(total);

        int id = hasil.INSERT(con);
        if (id != -1) {
            rincian.forEach((t) -> {
                t.setPenjual(id);
                if (t.INSERT(con)) {
                    boolean i = false;
                }

            });
            mejaDipilih.setAtas_nama(atasnama.getText());
            mejaDipilih.setNo_meja(Integer.parseInt(nmeja.getText()));

            if (mejaDipilih.update(con)) {
                JOptionPane.showMessageDialog(this, "tersimpan");
            }
        }

        konten.removeAll();
        konten.add(order);
        konten.repaint();
        konten.revalidate();

        DefaultTableModel m = (DefaultTableModel) tableorder.getModel();
        m.setRowCount(0);
        totalbayar.setText(null);
        atasnama.setText(null);
        nmeja.setText(null);
        rincian.clear();

        loadorder();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int y = JOptionPane.showConfirmDialog(this, "yakin dihapus");
        if (y == 0) {
            rincian.remove(tableorder.getSelectedRow());
            ((DefaultTableModel) tableorder.getModel()).removeRow(tableorder.getSelectedRow());
        }
        int total = 0;
        for (rincian_order order : rincian) {
            total += order.getHarga() * order.getTotalbarang();
        }
        totalbayar.setText("Rp. " + (total));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        konten.removeAll();
        konten.add(order);
        konten.repaint();
        konten.revalidate();

        loadorder();

    }//GEN-LAST:event_jButton7ActionPerformed

    private void bayartKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayartKeyTyped
char bilangan = evt.getKeyChar();
if(!(Character.isDigit(bilangan))){
    evt.consume();
}
    }//GEN-LAST:event_bayartKeyTyped

    private void bayartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayartKeyReleased
String byr = bayart.getText();
if(byr.isEmpty()){
    byr="0";
}
final int total = Integer.parseInt(totalt.getText());
final int bayar = Integer.parseInt(byr);
uangkembali.setText(String.valueOf(bayar-total));
    }//GEN-LAST:event_bayartKeyReleased
private void printRecord(JPanel panel){
    PrinterJob printerJob=PrinterJob.getPrinterJob();
    printerJob.setJobName("Print Record");
    printerJob.setPrintable(new Printable() {
        @Override
        public int print(Graphics graphics, PageFormat pf, int pagei) throws PrinterException {
            if (pagei > 0){
                return Printable.NO_SUCH_PAGE;
            }
        
            Graphics2D graphics2D = (Graphics2D)graphics;
            graphics2D.translate(pf.getImageableX() *2, pf.getImageableY()*2);
            graphics2D.scale(1,1);
            panel.paint(graphics2D);
            return Printable.PAGE_EXISTS;
        }
    });
    boolean returningResult = printerJob.printDialog();
    if (returningResult){
        try{
            printerJob.print();
        }catch(PrinterException printerException){
            JOptionPane.showMessageDialog(this, "print error" + printerException.getMessage());
        }
        
    }
}
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
printRecord(print);
    }//GEN-LAST:event_jButton8ActionPerformed
    private void loaddata() {
        panelgridbarang.removeAll();
        List<mbarang> bList = new mbarang().get(con);
        bList.forEach((t) -> {
            panelgridbarang.add(new TemplateBarang(t, this));

        });
        panelgridbarang.revalidate();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new home(1).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JLabel atasnama;
    public javax.swing.JTextField bayart;
    private javax.swing.JButton bmenu;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton buttonorder;
    private javax.swing.JPasswordField cpassword;
    private javax.swing.JPanel entrib;
    private javax.swing.JPanel entrim;
    private javax.swing.JPanel entrior;
    public javax.swing.JPanel entrit;
    private javax.swing.JPanel glporan;
    private javax.swing.JTextField hakakses;
    private javax.swing.JPanel home2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton jbarang;
    private javax.swing.JButton jentri;
    private javax.swing.JButton jhome;
    private javax.swing.JButton jlaporan;
    private javax.swing.JButton jorder;
    private javax.swing.JButton jtran;
    private keeptoo.KGradientPanel kGradientPanel2;
    public javax.swing.JPanel konten;
    private javax.swing.JLabel namalabel;
    private javax.swing.JTextField namap;
    public javax.swing.JLabel namat;
    private javax.swing.JLabel nmeja;
    public javax.swing.JLabel nomet;
    private javax.swing.JPanel order;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelgridbarang;
    private javax.swing.JPanel panelgridorder;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel pemesanan;
    private javax.swing.JPanel print;
    public javax.swing.JTable tableorder;
    private javax.swing.JPanel tambahakun;
    public javax.swing.JLabel tanggalt;
    public javax.swing.JTextField tatasnama;
    public javax.swing.JTextField tnomeja;
    public javax.swing.JLabel totalbayar;
    public javax.swing.JLabel totalbayar1;
    public javax.swing.JTextField totalt;
    public javax.swing.JTable ttrant;
    public javax.swing.JTextField uangkembali;
    private javax.swing.JPanel wadahm;
    private javax.swing.JPanel wadahmeja;
    // End of variables declaration//GEN-END:variables

}
