/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flogin;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.hasil_order;
import model.mbarang;
import model.rincian_order;

/**
 *
 * @author BoiPasta
 */
public class orderan extends javax.swing.JPanel {

    home transfer;
    hasil_order order;

    public orderan(home transfer, hasil_order order, Connection c) {
        this.transfer = transfer;
        this.order = order;
        initComponents();
        mejano.setText(String.valueOf(order.getNomeja()));
        namaatas.setText(order.getAtasnama());
        total.setText(String.valueOf(order.getTotal()));
        List<rincian_order> rincian = new rincian_order().get(c, order.getId());

        rincian.forEach((t) -> {
            mbarang mb = new mbarang().get(c, t.getBarang());
            DefaultTableModel m = (DefaultTableModel) ordertable.getModel();
            m.addRow(new Object[]{mb.getNamabarang(), t.getTotalbarang(), mb.getHarga()});
            System.out.println(t.getBarang());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        mejano = new javax.swing.JLabel();
        namaatas = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        mejano1 = new javax.swing.JLabel();
        namaatas1 = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 153, 204)));

        ordertable.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Pesanan", "Jumlah", "harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ordertable.setFocusable(false);
        ordertable.setGridColor(new java.awt.Color(255, 255, 255));
        ordertable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ordertable.setRowHeight(20);
        ordertable.setSelectionBackground(new java.awt.Color(0, 102, 204));
        ordertable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ordertable);

        mejano.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mejano.setText("jLabel1");

        namaatas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        namaatas.setText("jLabel2");

        total.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        total.setText("jLabel4");

        mejano1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mejano1.setText("No meja");

        namaatas1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        namaatas1.setText("nama");

        total1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        total1.setText("Total Rp.");

        jButton1.setText("P");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(namaatas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(namaatas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(mejano1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mejano)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(total1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mejano)
                        .addComponent(mejano1))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total)
                    .addComponent(namaatas)
                    .addComponent(namaatas1)
                    .addComponent(total1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        transfer.nomet.setText(mejano.getText());
        transfer.namat.setText(namaatas.getText());
        transfer.tanggalt.setText(order.getTgl_order());
        transfer.totalt.setText(total.getText());
        transfer.ttrant.setModel(ordertable.getModel());
        transfer.konten.removeAll();
        transfer.konten.add(transfer.entrit);
        transfer.konten.repaint();
        transfer.konten.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mejano;
    private javax.swing.JLabel mejano1;
    private javax.swing.JLabel namaatas;
    private javax.swing.JLabel namaatas1;
    public javax.swing.JTable ordertable;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total1;
    // End of variables declaration//GEN-END:variables
}
