/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flogin;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import model.mbarang;
import model.rincian_order;

/**
 *
 * @author BoiPasta
 */
public class TemplateBarang extends javax.swing.JPanel {

    home h;
    mbarang nbarang;

    public TemplateBarang(mbarang nbarang, home h) {
        this.h = h;
        this.nbarang = nbarang;
        initComponents();

        image.setIcon(new ImageIcon(nbarang.getGambarmakanan()));
        harga.setText("Rp. " + nbarang.getHarga());
        namamakanan.setText(nbarang.getNamabarang());
        bpesan.setText("Rp. " + nbarang.getHarga());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        btambah = new javax.swing.JButton();
        bkurang = new javax.swing.JButton();
        namamakanan = new javax.swing.JLabel();
        et_jumlah = new javax.swing.JTextField();
        bpesan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        image.setBackground(new java.awt.Color(204, 204, 255));
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dad.png"))); // NOI18N
        image.setText("jLabel1");

        harga.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        harga.setText("Rp.5.000");

        btambah.setText("+");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        bkurang.setText("-");
        bkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkurangActionPerformed(evt);
            }
        });

        namamakanan.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        namamakanan.setText("Coca Cola");

        et_jumlah.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_jumlah.setText("1");

        bpesan.setText("Rp.");
        bpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpesanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(et_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga)
                            .addComponent(namamakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bpesan, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(namamakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(harga)
                        .addGap(49, 49, 49)
                        .addComponent(bpesan))
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btambah)
                    .addComponent(bkurang)
                    .addComponent(et_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        int currentTotal = Integer.parseInt(et_jumlah.getText());
        int hargaBarang = nbarang.getHarga();

        currentTotal++;
        hargaBarang *= currentTotal;
        et_jumlah.setText(String.valueOf(currentTotal));
        bpesan.setText("Rp. " + hargaBarang);
    }//GEN-LAST:event_btambahActionPerformed

    private void bkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkurangActionPerformed
        int currentTotal = Integer.parseInt(et_jumlah.getText());
        int hargaBarang = nbarang.getHarga();

        if (currentTotal > 1) {
            currentTotal--;
            hargaBarang *= currentTotal;
            et_jumlah.setText(String.valueOf(currentTotal));
            bpesan.setText("Rp. " + hargaBarang);
        }
    }//GEN-LAST:event_bkurangActionPerformed

    private void bpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpesanActionPerformed
        DefaultTableModel model = (DefaultTableModel) h.tableorder.getModel();
        model.addRow(new Object[]{
            nbarang.getNamabarang(),
            et_jumlah.getText(),
            harga.getText(),
            bpesan.getText()});

        rincian_order or = new rincian_order();
        or.setBarang(nbarang.getId());
        or.setTotalbarang(Integer.parseInt(et_jumlah.getText()));
        or.setHarga(nbarang.getHarga());
        h.rincian.add(or);
        int total = 0;
        for (rincian_order order : h.rincian) {
            total += order.getHarga() * order.getTotalbarang();
        }
        h.totalbayar.setText("Rp. " + (total));
    }//GEN-LAST:event_bpesanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkurang;
    private javax.swing.JButton bpesan;
    private javax.swing.JButton btambah;
    private javax.swing.JTextField et_jumlah;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel image;
    private javax.swing.JLabel namamakanan;
    // End of variables declaration//GEN-END:variables
}
